pipeline {
    agent any
    stages {
        stage('Micro service Go provision') {
            steps {
                sh("cd 3-devops/antonio-azambuja/tema20/baking-calc-ami/ && packer build calculator.json")
            }
        }
    }
}