pipeline {
    agent any
    stages {
        stage('ELK Logstash provision') {
            steps {
                sh("cd 3-devops/antonio-azambuja/tema20/baking-elk/logstash/ && packer build logstash.json")
            }
        }
    }
}